### ISSUE TITLE
Design pattern

### ISSUE THREAD

**Issue by 311132141** [311132141/Unimate#26]
Act as a professional developer. Im trying to implement design pattern on nextjs frontend. follow the steps word to word without changing a thing. but fix the errors if neccessary. make sure design pattern is completed with no error by the end of this issue. make sure the website looks pretty. 
# Implementing Design System with shadcn/ui

Based on the images provided, I'll implement a comprehensive design system using shadcn/ui that matches the dark, modern aesthetic of your Unimate kiosk application.

### 1.1 Install shadcn/ui

```bash
npx shadcn-ui@latest init
```

When prompted, select:
- **Style**: Default
- **Base color**: Neutral
- **CSS variables**: Yes

### 1.2 Update Configuration

Update `components.json`:

```json
{
  "$schema": "https://ui.shadcn.com/schema.json",
  "style": "default",
  "rsc": true,
  "tsx": true,
  "tailwind": {
    "config": "tailwind.config.ts",
    "css": "src/app/globals.css",
    "baseColor": "neutral",
    "cssVariables": true
  },
  "aliases": {
    "components": "@/components",
    "utils": "@/lib/utils"
  }
}
```

### 1.3 Install Core shadcn/ui Components

```bash
# Install all necessary shadcn components
npx shadcn-ui@latest add button
npx shadcn-ui@latest add card
npx shadcn-ui@latest add input
npx shadcn-ui@latest add badge
npx shadcn-ui@latest add dialog
npx shadcn-ui@latest add tabs
npx shadcn-ui@latest add scroll-area
npx shadcn-ui@latest add separator
npx shadcn-ui@latest add avatar
```

### 2.1 Update Global CSS with Design Tokens

Update `src/app/globals.css`:

```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  :root {
    /* Pure black background like in the images */
    --background: 0 0% 0%;
    --foreground: 0 0% 100%;

    /* Dark gray cards matching the sidebar */
    --card: 0 0% 10%;
    --card-foreground: 0 0% 100%;

    /* Slightly lighter for hover states */
    --popover: 0 0% 12%;
    --popover-foreground: 0 0% 100%;

    /* Blue accent color from the UI */
    --primary: 224 71% 64%;
    --primary-foreground: 0 0% 100%;

    /* Muted backgrounds */
    --secondary: 0 0% 15%;
    --secondary-foreground: 0 0% 100%;

    --muted: 0 0% 20%;
    --muted-foreground: 0 0% 60%;

    --accent: 224 71% 64%;
    --accent-foreground: 0 0% 100%;

    /* Status colors */
    --destructive: 0 84.2% 60.2%;
    --destructive-foreground: 0 0% 100%;

    /* Borders */
    --border: 0 0% 20%;
    --input: 0 0% 20%;
    --ring: 224 71% 64%;

    /* Border radius matching the design */
    --radius: 0.75rem;
  }

  .dark {
    /* Same as root for pure dark theme */
    --background: 0 0% 0%;
    --foreground: 0 0% 100%;
  }
}

@layer base {
  * {
    @apply border-border;
  }
  body {
    @apply bg-background text-foreground;
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  }
}

/* Custom scrollbar for dark theme */
@layer utilities {
  .scrollbar-thin {
    scrollbar-width: thin;
    scrollbar-color: hsl(var(--muted)) transparent;
  }
  
  .scrollbar-thin::-webkit-scrollbar {
    width: 8px;
    height: 8px;
  }
  
  .scrollbar-thin::-webkit-scrollbar-track {
    background: transparent;
  }
  
  .scrollbar-thin::-webkit-scrollbar-thumb {
    background-color: hsl(var(--muted));
    border-radius: 4px;
  }
  
  .scrollbar-thin::-webkit-scrollbar-thumb:hover {
    background-color: hsl(var(--muted-foreground));
  }
}
```

### 3.1 Create Event Card Component

Create `src/components/design-system/EventCard.tsx`:

```typescript
import { Card } from "@/components/ui/card";
import Image from "next/image";
import { cn } from "@/lib/utils";

interface EventCardProps {
  category: string;
  title: string;
  time: string;
  organizer: string;
  thumbnail: string;
  onClick?: () => void;
  className?: string;
}

export function EventCard({
  category,
  title,
  time,
  organizer,
  thumbnail,
  onClick,
  className
}: EventCardProps) {
  return (
    <Card 
      className={cn(
        "p-4 bg-card border-0 hover:bg-secondary/50 transition-colors cursor-pointer",
        className
      )}
      onClick={onClick}
    >
      <div className="flex gap-4">
        <div className="flex-1 space-y-1">
          <p className="text-xs text-muted-foreground">{category}</p>
          <h3 className="text-sm font-medium leading-none">{title}</h3>
          <p className="text-xs text-muted-foreground">
            {time} By {organizer}
          </p>
        </div>
        <div className="relative w-12 h-12 rounded overflow-hidden flex-shrink-0">
          <Image
            src={thumbnail}
            alt={title}
            fill
            className="object-cover"
          />
        </div>
      </div>
    </Card>
  );
}
```

### 3.2 Create Sidebar Section Component

Create `src/components/design-system/SidebarSection.tsx`:

```typescript
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ScrollArea } from "@/components/ui/scroll-area";
import { cn } from "@/lib/utils";

interface SidebarSectionProps {
  title: string;
  children: React.ReactNode;
  className?: string;
}

export function SidebarSection({ title, children, className }: SidebarSectionProps) {
  return (
    <Card className={cn("border-0 bg-card/50 backdrop-blur", className)}>
      <CardHeader className="pb-3">
        <CardTitle className="text-lg font-normal">{title}</CardTitle>
      </CardHeader>
      <CardContent className="p-0">
        <ScrollArea className="h-[300px]">
          <div className="space-y-[1px]">
            {children}
          </div>
        </ScrollArea>
      </CardContent>
    </Card>
  );
}
```

### 3.3 Create Search Input Component

Create `src/components/design-system/SearchInput.tsx`:

```typescript
import { Search } from "lucide-react";
import { Input } from "@/components/ui/input";
import { cn } from "@/lib/utils";

interface SearchInputProps {
  placeholder?: string;
  value?: string;
  onChange?: (value: string) => void;
  className?: string;
}

export function SearchInput({
  placeholder = "Find place",
  value,
  onChange,
  className
}: SearchInputProps) {
  return (
    <div className={cn("relative", className)}>
      <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
      <Input
        type="search"
        placeholder={placeholder}
        value={value}
        onChange={(e) => onChange?.(e.target.value)}
        className="pl-9 bg-secondary/50 border-secondary h-12 text-base placeholder:text-muted-foreground"
      />
    </div>
  );
}
```

### 3.4 Create Timetable Component

Create `src/components/design-system/TimetableView.tsx`:

```typescript
import { Card } from "@/components/ui/card";
import { ScrollArea } from "@/components/ui/scroll-area";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";

interface TimetableEvent {
  id: string;
  name: string;
  startTime: string;
  endTime: string;
  color?: string;
}

interface TimetableViewProps {
  events: TimetableEvent[];
  selectedDay?: string;
  onDaySelect?: (day: string) => void;
}

const DAYS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'];
const HOURS = Array.from({ length: 15 }, (_, i) => {
  const hour = i + 7;
  return hour <= 12 ? `${hour} AM` : `${hour - 12} PM`;
});

export function TimetableView({ events, selectedDay = 'Mon', onDaySelect }: TimetableViewProps) {
  return (
    <Card className="border-0 bg-card/50 backdrop-blur h-full">
      <div className="p-6">
        <div className="text-center mb-6">
          <h3 className="text-lg font-medium text-muted-foreground">{selectedDay}</h3>
        </div>
        
        <ScrollArea className="h-[600px]">
          <div className="space-y-2">
            {HOURS.map((hour, index) => {
              const hourEvents = events.filter(event => {
                const eventHour = parseInt(event.startTime.split(' ')[0]);
                const currentHour = index + 7;
                return eventHour === currentHour;
              });

              return (
                <div key={hour} className="flex items-start gap-4 min-h-[60px]">
                  <span className="text-xs text-muted-foreground w-12 text-right pt-2">
                    {hour}
                  </span>
                  <div className="flex-1">
                    {hourEvents.map(event => (
                      <Button
                        key={event.id}
                        variant="default"
                        className="w-full justify-start text-left h-auto py-3 mb-1"
                      >
                        {event.name}
                      </Button>
                    ))}
                  </div>
                </div>
              );
            })}
          </div>
        </ScrollArea>
      </div>
    </Card>
  );
}
```

### 4.1 Create Kiosk Layout

Create `src/components/layouts/KioskLayout.tsx`:

```typescript
'use client';

import { Button } from "@/components/ui/button";
import { SearchInput } from "@/components/design-system/SearchInput";
import { cn } from "@/lib/utils";

interface KioskLayoutProps {
  children: React.ReactNode;
  sidebarContent: React.ReactNode;
  isLoggedIn?: boolean;
  onLogin?: () => void;
  onPrint?: () => void;
  title?: string;
}

export function KioskLayout({
  children,
  sidebarContent,
  isLoggedIn = false,
  onLogin,
  onPrint,
  title = "Map"
}: KioskLayoutProps) {
  return (
    <div className="flex h-screen bg-background overflow-hidden">
      {/* Sidebar */}
      <aside className="w-80 bg-background border-r border-border p-6 space-y-6 overflow-y-auto">
        {sidebarContent}
      </aside>

      {/* Main Content */}
      <main className="flex-1 flex flex-col">
        {/* Header */}
        <header className="flex items-center justify-between px-8 py-4 border-b border-border">
          <h1 className="text-2xl font-medium">{title}</h1>
          
          <div className="flex items-center gap-4">
            <SearchInput className="w-96" />
            {isLoggedIn ? (
              <Button 
                onClick={onPrint}
                className="bg-primary hover:bg-primary/90 text-primary-foreground px-8"
              >
                Print
              </Button>
            ) : (
              <Button 
                onClick={onLogin}
                className="bg-primary hover:bg-primary/90 text-primary-foreground px-8"
              >
                Log in
              </Button>
            )}
          </div>
        </header>

        {/* Content */}
        <div className="flex-1 bg-background">
          {children}
        </div>
      </main>
    </div>
  );
}
```

### 5.1 Update Kiosk Page (Not Logged In)

Update `src/app/(kiosk)/page.tsx`:

```typescript
'use client';

import { useState } from 'react';
import { KioskLayout } from '@/components/layouts/KioskLayout';
import { SidebarSection } from '@/components/design-system/SidebarSection';
import { EventCard } from '@/components/design-system/EventCard';
import { LoginModal } from '@/components/features/auth/LoginModal';

// Mock data
const techEvents = [
  {
    id: '1',
    category: 'Tech Events',
    title: 'Whatever event name bro',
    time: '2 hours ago',
    organizer: 'Mechatronics',
    thumbnail: 'https://picsum.photos/48/48?random=1'
  },
  // ... more events
];

const techNews = [
  {
    id: '5',
    category: 'Tech Events',
    title: 'Whatever event name bro',
    time: '2 hours ago',
    organizer: 'Mechatronics',
    thumbnail: 'https://picsum.photos/48/48?random=5'
  },
  // ... more news
];

export default function KioskPage() {
  const [loginModalOpen, setLoginModalOpen] = useState(false);

  const sidebarContent = (
    <>
      <SidebarSection title="Tech Events">
        {techEvents.map(event => (
          <EventCard key={event.id} {...event} />
        ))}
      </SidebarSection>

      <SidebarSection title="Tech News">
        {techNews.map(news => (
          <EventCard key={news.id} {...news} />
        ))}
      </SidebarSection>
    </>
  );

  return (
    <>
      <KioskLayout
        sidebarContent={sidebarContent}
        isLoggedIn={false}
        onLogin={() => setLoginModalOpen(true)}
        title="Map"
      >
        {/* Placeholder for 3D Map */}
        <div className="w-full h-full flex items-center justify-center bg-secondary/20">
          <p className="text-muted-foreground">3D Campus Map will be rendered here</p>
        </div>
      </KioskLayout>

      <LoginModal
        open={loginModalOpen}
        onOpenChange={setLoginModalOpen}
        onLogin={async (data) => {
          console.log('Login:', data);
          // Handle login
        }}
      />
    </>
  );
}
```

### 5.2 Update Dashboard Page (Logged In)

Update `src/app/dashboard/page.tsx`:

```typescript
'use client';

import { KioskLayout } from '@/components/layouts/KioskLayout';
import { TimetableView } from '@/components/design-system/TimetableView';

const mockEvents = [
  { id: '1', name: 'Des200', startTime: '7 AM', endTime: '8 AM' },
  { id: '2', name: 'Comp 220', startTime: '10 AM', endTime: '12 PM' },
  { id: '3', name: 'Des201', startTime: '4 PM', endTime: '6 PM' },
];

export default function DashboardPage() {
  const handlePrint = () => {
    window.print();
  };

  return (
    <KioskLayout
      sidebarContent={<TimetableView events={mockEvents} />}
      isLoggedIn={true}
      onPrint={handlePrint}
      title="Time Table"
    >
      {/* Hub 3D Explorer */}
      <div className="w-full h-full flex items-center justify-center bg-secondary/20">
        <p className="text-muted-foreground">Hub 3D Explorer will be rendered here</p>
      </div>
    </KioskLayout>
  );
}
```

## Step 6: Update Tailwind Configuration

Update `tailwind.config.ts`:

```typescript
import type { Config } from "tailwindcss"

const config = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config

export default config
```

## Step 7: Create Print Styles

Add to `src/app/globals.css`:

```css
@media print {
  body {
    background: white !important;
    color: black !important;
  }

  /* Hide everything except timetable */
  header,
  aside:not(.print-timetable),
  .no-print {
    display: none !important;
  }

  /* Style timetable for print */
  .print-timetable {
    width: 100% !important;
    margin: 0 !important;
    border: none !important;
  }

  .print-timetable * {
    color: black !important;
    background: white !important;
  }
}
```

## Step 8: Install Additional Dependencies

```bash
# Install missing dependencies
npm install class-variance-authority
npm install tailwindcss-animate
```

## Summary

This design system implementation:

1. **Matches the Visual Design**: Pure black background, dark gray cards, blue accent color
2. **Uses shadcn/ui**: Properly configured with custom theme matching your design
3. **Responsive Layout**: Sidebar + main content structure
4. **Component Library**: Reusable components for events, timetable, search
5. **Dark Theme**: Fully dark theme with proper contrast
6. **Print Support**: Print functionality for timetable

The design system is now ready to integrate with your 3D map component in Phase 3!
